// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5oaBWfpi-AqfB1iJNbQs6S3fJuwRX6ms',
    appId: '1:499792878646:web:eb1dceded41a10d0538c97',
    messagingSenderId: '499792878646',
    projectId: 'flutter-tutorial-fb69b',
    authDomain: 'flutter-tutorial-fb69b.firebaseapp.com',
    databaseURL: 'https://flutter-tutorial-fb69b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-tutorial-fb69b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCablvz-rUoaEl9E-EcmznslHKMU2uP2H8',
    appId: '1:499792878646:android:58927ea2192125a9538c97',
    messagingSenderId: '499792878646',
    projectId: 'flutter-tutorial-fb69b',
    databaseURL: 'https://flutter-tutorial-fb69b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-tutorial-fb69b.appspot.com',
  );
}
